"""
defaults.py:
    Default values for various settings.

Author: Corwin Brown
Date: 05/07/2016
"""
from __future__ import absolute_import


class StasipyDefaults:
    sample_length = 40
    default_site_config = {
        'maintainer': '<put your name here>',
        'email': '<put your email here>',
        'description': 'A website generated by "StasiPy"',
        'sample_length': sample_length,
        'nav_items': [
            {
                'title': 'Home',
                'href': '/'
            }
        ],
        'time_format': '%m/%d/%Y'
    }
