"""
defaults.py:
    Default values for various settings.

Author: Corwin Brown
Date: 05/07/2016
"""
from __future__ import absolute_import


class StasipyDefaults:
    summary_length = 40
    default_site_config = {
        'maintainer': 'Your Name',
        'maintainer_email': 'your_email@email.com',
        'description': 'A website generated by "StasiPy"',
        'summary_length': summary_length,
        'nav_items': [
            {
                'title': 'Home',
                'href': '/'
            }
        ],
        'time_format': '%m/%d/%Y'
    }
